live_config_reload = true

[window]
padding = { x = 6, y = 6 }
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "Both"

[colors]

[colors.primary]
background = "#ffffff"
foreground = "#000000"

[terminal]
osc52 = "CopyPaste"

[font]
normal = { family = "ComicShannsMono Nerd Font" }
bold = { family = "ComicShannsMono Nerd Font" }
bold_italic = { family = "ComicShannsMono Nerd Font" }
italic = { family = "ComicShannsMono Nerd Font" }
size = 13

[font.offset]
x = 1
y = 5

[cursor]
style = { shape = "Block" }

