format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$time\
$character"""

add_newline = false

[username]
show_always = true
style_user = ""
style_root = ""
format = '[\[$user\]]($style)'
disabled = false

[hostname]
ssh_only = false
ssh_symbol = ""
style = ""
format = '[\[$ssh_symbol$hostname\]]($style)'

[character]
format = ''

[directory]
style = ""
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"
home_symbol = "~"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
style = ""
symbol = ""
format = '[\[$symbol $branch\] ]($style)'

[git_status]
disabled = true
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)'
